<?php
// DO NOT EDIT THIS FILE
require_once(__DIR__ . '/lib/vendor/autoload.php');
require_once('env-config.php' );               // ENVIORNMENT & DB DEFINITIONS
require_once('lib/config/application.php' );   // WP & ENV DEFINITIONS
require_once(ABSPATH . 'wp-settings.php');      // BOOTUP WP